apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-101
  description: An example of a Backstage application.
  tags:
    - web-app
    - catalog
    - POC
  # Example for optional annotations
  annotations:
  #   github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: cristian-hurdubai-sv_bootstrap
spec:
  type: website
  owner: backstage-boys 
  lifecycle: experimental
