site_name: Backstage HOWTO
site_description: Documentation of the Backstage POC

docs_dir: ./docs

plugins:
  - techdocs-core

nav:
  - How to build backstage:
    - Getting Started: getting-started.md
    - Docker: docker.md
    - Dockerization: dockerisation.md

  - Plugins:
    - SonarQube: sonarqube.md

  - How to use Backstage:
    - For users: for-users/index.md
    - For maintainers: for-maintainers/index.md
