site_name: Backstage HOWTO
site_description: Documentation of the Backstage POC

docs_dir: ./docs

plugins:
  - techdocs-core

nav:
  - How to build the Backstage application:
    - Getting Started: getting-started.md
    - Docker: docker.md
    - Dockerization: dockerisation.md
    - DataBase: database.md

  - Plugins:
    - SonarQube: plugins/sonarqube.md
    - Search: plugins/search.md

  - How to use Backstage:
    - For users: for-users/index.md
    - For maintainers: for-maintainers/index.md
