site_name: Backstage HOWTO
site_description: Documentation of the Backstage POC

docs_dir: ./docs

plugins:
  - techdocs-core

nav:
  - Backstage:
    - Getting Started: getting-started.md
    - Docker: docker.md
